language: php
php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source
    - composer require satooshi/php-coveralls:dev-master
    - composer install
script: phpunit
after_script:
  - php vendor/bin/coveralls -v