language: php
php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1
before_script:
    - composer require satooshi/php-coveralls:dev-master
    - composer require davidkevork/steemphp
    - composer install
script: phpunit
after_script:
  - php vendor/bin/coveralls -v
