language: php
php:
  - 5.6
before_script:
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls:dev-master
script: phpunit
after_script:
  - php vendor/bin/coveralls -v